import type { ResumeData } from '../types/resume';

export const exportResumeToJson = (resumeData: ResumeData) => {
  return {
    schemaVersion: resumeData.schemaVersion,
    theme: resumeData.theme,
    personalInfo: {
      fullName: resumeData.personalInfo?.fullName || '',
      jobTitle: resumeData.personalInfo?.jobTitle || '',
      email: resumeData.personalInfo?.email || '',
      phone: resumeData.personalInfo?.phone || '',
      address: resumeData.personalInfo?.address || '',
      linkedinUrl: resumeData.personalInfo?.linkedinUrl || '',
      githubUrl: resumeData.personalInfo?.githubUrl || '',
      gitlabUrl: resumeData.personalInfo?.gitlabUrl || '',
      portfolioUrl: resumeData.personalInfo?.portfolioUrl || '',
      whatsapp: resumeData.personalInfo?.whatsapp || '',
      dateOfBirth: resumeData.personalInfo?.dateOfBirth || '',
      nationality: resumeData.personalInfo?.nationality || '',
      gender: resumeData.personalInfo?.gender || '',
      summary: resumeData.personalInfo?.summary || '',
    },
    experience: (resumeData.experience || []).map((exp) => ({
      company: exp.company || '',
      position: exp.position || '',
      location: exp.location || '',
      startDate: exp.startDate || '',
      endDate: exp.endDate || '',
      current: exp.current || false,
      format: exp.format || 'paragraph',
      description: exp.description || '',
      bullets: exp.bullets || [],
      experienceProjects: (exp.experienceProjects || []).map((proj) => ({
        name: proj.name || '',
        projectDescription: proj.projectDescription || '',
        format: proj.format || 'bullets',
        description: proj.description || '',
        bullets: proj.bullets || [],
        liveLink: proj.liveLink || '',
      })),
    })),
    education: (resumeData.education || []).map((edu) => ({
      institution: edu.institution || '',
      degree: edu.degree || '',
      startDate: edu.startDate || '',
      endDate: edu.endDate || '',
      description: edu.description || '',
    })),
    skills: (resumeData.skills || []).map((skill) => ({
      category: skill.category || '',
      skills: skill.skills || [],
    })),
    projects: (resumeData.projects || []).map((proj) => ({
      name: proj.name || '',
      description: proj.description || '',
      technologies: proj.technologies || [],
      links: (proj.links || []).map((link) => ({
        label: link.label || '',
        liveUrl: link.liveUrl || '',
        githubUrl: link.githubUrl || '',
      })),
      highlights: proj.highlights || [],
      startDate: proj.startDate || '',
      endDate: proj.endDate || '',
    })),
    languages: (resumeData.languages || []).map((lang) => ({
      name: lang.name || '',
      level: lang.level || '',
    })),
    interests: (resumeData.interests || []).map((interest) => ({
      name: interest.name || '',
    })),
    interestsFormat: resumeData.interestsFormat,
    interestsParagraph: resumeData.interestsParagraph || '',
    certifications: (resumeData.certifications || []).map((cert) => ({
      name: cert.name || '',
      issuer: cert.issuer || '',
      date: cert.date || '',
      url: cert.url || '',
    })),
    sectionLabels: resumeData.sectionLabels,
    sectionVisibility: resumeData.sectionVisibility,
    coverLetter: resumeData.coverLetter,
  };
};
